---
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

name: Build

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_REGISTRY_IMAGE: ${{ secrets.DOCKER_REGISTRY_IMAGE }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_ZONE: ${{ secrets.GOOGLE_ZONE }}
  GOOGLE_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICE_KEY_HUB }}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY_IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Login to GCloud
        run: |
          echo ${{ env.GOOGLE_SERVICE_KEY }} | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud --quiet config set project ${{ env.GOOGLE_PROJECT }}
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin ${{ env.DOCKER_REGISTRY }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.DOCKER_REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
